#!/usr/bin/env python
from PIL import Image
from resizeimage import resizeimage
import sys, os

if len(sys.argv) < 4:
    print "overlay [background] [overlay] [outfile]"
else:
    back, overlay = map(Image.open, sys.argv[1:3])
    try:
        back = resizeimage.resize_cover(back, overlay.size)
        back = back.convert('L')
        out = Image.new("RGBA", back.size)
        out.paste(back)
        out.paste(overlay, (0, 0), overlay)
        out.save(sys.argv[3], "PNG")
    except Exception as e:
        print e
        sys.exit(1)
